Разметка внутренней страницы
htmlacademy-htmlcss/1954435-sedona-33 pull request #4
Opened 2022-02-01 20:44 UTC by AndrewSamohvalov

2022-02-02 14:10 UTC, costigans requested changes

2022-02-02 14:10 UTC, costigans commented on catalog.html
> +					<a class="breadcrumbs-link">&gt; Гостиницы</a>
Символ `&gt;` здесь лишний

2022-02-02 14:10 UTC, costigans commented on catalog.html
> +						<input type="text" name="price-from" placeholder="0 от ">
Неверный `placholder`

2022-02-02 14:10 UTC, costigans commented on catalog.html
> +						<input type="text" name="price-to" placeholder="9000 до">
Неверный `placholder`

2022-02-02 14:10 UTC, costigans commented on catalog.html
> +					<img class="hotel-card-image" src="" width="" height="" alt="Гостиница Amara Resort & Spa">
А значение атрибутов где?

2022-02-02 21:54 UTC, AndrewSamohvalov commented on catalog.html
> +						<input type="text" name="price-from" placeholder="0 от ">
Доброе утро, Константин! Я написал 2 решения для placeholder, но так и не уверен нив одном из них.
На лайве сказали что это поле с ползунком (range) будем позже проходить в дальнейшем.

2022-02-05 09:40 UTC, costigans commented on catalog.html
> +						<input type="text" name="price-from" placeholder="0 от ">
Да, но этот инпут не для ползунка, а для поля ввода числа

2022-02-05 09:43 UTC, costigans requested changes

2022-02-05 09:43 UTC, costigans commented on catalog.html
> +						<input type="text" id="price-min" name="price-from" placeholder="0">
Не тот тип

2022-02-05 09:43 UTC, costigans commented on catalog.html
> +						<input type="text" id="price-min" name="price-from" placeholder="0">
А слово «От» гдебудешь размешать?

2022-02-05 09:43 UTC, costigans commented on catalog.html
> +
Удаляй такое сразу. Гит всё хранит и ты можешь в нём подсмотреть прошлую реализацию

2022-02-06 16:45 UTC, AndrewSamohvalov commented on catalog.html
> +						<input type="text" id="price-min" name="price-from" placeholder="0">
правильный тип будет number исправил. А вот слово ОТ куда размещать не понял.

2022-02-11 19:52 UTC, merged